services:
  minecraft:
    container_name: server
    build: .
    restart: unless-stopped
    volumes:
      - ./data:/data:rw
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
      - 25565:25565
    deploy:
      resources:
        limits:
          # cpus: '3'
          memory: 10gb
